### ISSUE TITLE
New ?x_rate_megabits contradicts convention

### ISSUE THREAD

**Issue by NightTsarina** [brandond/homeplug_exporter#2]
Hi again!

As I was preparing the debian package with the latest commits, I noticed this change:

```diff
--- a/README.md
+++ b/README.md
@@ -47,8 +47,8 @@ 
 # TYPE homeplug_exporter_build_info gauge
 # HELP homeplug_network_id Logical network information
 # TYPE homeplug_network_id gauge
-# HELP homeplug_station_rx_rate_bytes Average PHY Rx data rate
-# TYPE homeplug_station_rx_rate_bytes gauge
-# HELP homeplug_station_tx_rate_bytes Average PHY Tx data rate
-# TYPE homeplug_station_tx_rate_bytes gauge
+# HELP homeplug_station_rx_rate_megabits Average PHY Rx data rate
+# TYPE homeplug_station_rx_rate_megabits gauge
+# HELP homeplug_station_tx_rate_megabits Average PHY Tx data rate
+# TYPE homeplug_station_tx_rate_megabits gauge
 ```
```

I think this is not a good idea, as the core devs have been trying to unify metric units as much as possible in the past couple of years, and `bytes` is the preferred base unit for this. See https://prometheus.io/docs/practices/naming/#base-units

**Comment by NightTsarina** [comment]
I see in the commit history that you had issues with this.. But the last change before you reverted it seems to be doing the right thing, except that it is missing the bit to byte conversion:
```
float64(station.TxRate) * 1024 * 1024, station.Address.String(), strconv.FormatInt(int64(station.TEI), 10))
```

**Comment by brandond** [comment]
Yeah, I was mucking about with it and ended up just sticking with the native unit since I realized I was doing a bunch of math to convert from megabit to bytes in the exporter, and then converting from bytes back to megabits in Grafana to display the line rate on my dashboard. Just seemed like needless complexity.

I'd welcome a PR, but at the moment I can't quite be arsed to fix it myself.
